version: '3.8'
services:
  backend:
    build: ./server
    container_name: doctor_server
    ports:
      - 9999:9999
    volumes:
      - ./server:/app
    networks:
      - backend
      - frontend
    depends_on:
      - database
  frontend:
    build: ./doctor-appointment
    container_name: doctor_frontend
    ports:
      - 80:5173
    volumes:
      - ./doctor-appointment:/app
    networks:
      - frontend
  database:
    image: mongo:latest
    container_name: doctor_db
    ports:
      - 27017:27017
    volumes:
      - doctor_data:/data/db
    networks:
      - backend
volumes:
  doctor_data:
networks:
  backend:
  frontend: